"colorscheme punchy-cyberpunk-hc
"colorscheme sunbather
colorscheme cyberpunk-neon

set t_Co=256

set nu
set mouse=a

set cul
set ruler
"set spell

set termguicolors
syntax on
filetype plugin indent on

set tabstop=4
set shiftwidth=4
set noexpandtab
set copyindent
set preserveindent
set softtabstop=0
set smarttab
set autoindent
set autochdir
set hidden
set foldenable
set nojoinspaces
set showcmd
"set encoding=UTF-8

set splitright
set splitbelow

set showmatch
set incsearch
set hlsearch
"set ignorecase
set smartcase

set backspace=2

"set textwidth=79

"Plugin options
let g:airline#extensions#tabline#enabled = 1
let g:airline_section_b = '%{strftime("%c")}'
let g:airline_section_y = 'BN: %{bufnr("%")}'
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
